Merged canvases/layers into single container unit, unified drawables/containers as visuals
Computr1x/ExNihilo pull request #2
Opened 2022-08-15 13:11 UTC by IgorTimofeev

2022-08-15 22:15 UTC, Computr1x requested changes
please fix two comments

2022-08-15 22:15 UTC, Computr1x commented on ExNihilo/Random/RandomManager.cs
> +    private static Random? _Random;
_Random must be non-static in case of randomization of different containers in different threads. In this situation, another thread can reset the seed and different image will be generated.

2022-08-15 22:15 UTC, Computr1x commented on ExNihilo/Base/Visuals/Container.cs
> +    public override void Render(Image image, GraphicsOptions graphicsOptions)
Render does not take into account the situation with rendering a container without children and effects, in which case nothing will be rendered.
ExNihilo.Tests.GeneratorTest passes, but all images are rendered without Color.Orange background

2022-08-16 09:21 UTC, IgorTimofeev commented on ExNihilo/Base/Visuals/Container.cs
> +    public override void Render(Image image, GraphicsOptions graphicsOptions)
@Computr1x 
![image](https://user-images.githubusercontent.com/11760002/184844998-acd70a48-3ca7-4944-afef-eb4c673699bf.png)

2022-08-16 10:12 UTC, merged